name: Tests
on: push
env:
  superviser_repo: "Gotfrid/project-superviser"
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv python install
      - run: uv sync --all-extras --dev
      - run: uv run pytest
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ env.superviser_repo }}
          submodules: true
      - uses: extractions/setup-just@v2
      - run: |
          cd ${{ github.event.repository.name }}
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch
          git checkout ${{ github.ref_name }}
          cd ..
      - run: just test
  update_submodule_ref:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: ${{ env.superviser_repo }}
          token: ${{ secrets.PAT }}
          submodules: true
      - run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add --all
          git commit -m "Update submodules: ${{github.ref_name}}" || echo "No changes to commit"
          git push
